apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "device-workflow.backendName" . }}-routes
  labels:
    app.kubernetes.io/name: {{ include "device-workflow.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "list"]
