apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "device-workflow.backendName" . }}-routes
  labels:
    app.kubernetes.io/name: {{ include "device-workflow.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "device-workflow.backendName" . }}-routes
subjects:
  - kind: ServiceAccount
    name: {{ if .Values.backend.serviceAccount.name }}{{ .Values.backend.serviceAccount.name }}{{ else }}{{ include "device-workflow.backendName" . }}{{ end }}
    namespace: {{ .Release.Namespace }}
